version: "3.8"
services:
  node-app:
    container_name: node
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000