version: "3.8"
services:
  node-app:
    container_name: node
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    stdin_open: true